#dev
deployment:
  strategy: rsync
  user: root
  from: ./.mage/artifact/
  to: /var/www/deploy
  document-root: '/var/www/html'
releases:
  enabled: true
  max: 5
  symlink: current
  directory: releases
hosts:
  - "94.247.144.211"
tasks:
  pre-deploy:
    - typo3-artifact:
        excludes:
          - /bin
          - /deployment
          - /fileadmin
          - /typo3
          - /typo3temp
          - /uploads
          - composer.lock
          - /composer.json
          - /index.php
          - atlassian-ide-plugin.xml
          - .editorconfig
          - .git*
          - .idea
          - .mage
          - .vagrant
          - bower_components
          - node_modules
          - Vagrantfile
          - README.md
  on-deploy:
    - filesystem/permissions-writable-by-web-server:
        paths:
            - /var/www/deploy
            - /var/www/html
        recursive: true
        checkPathsExist: true
  post-release:
    - general/manually:
        - rm typo3conf/realurl_autoconf.php
    - clear-op-cache: {frontend-url: 'http://stage.tuga.at'}
    - typo3-console: {copyEntryPoint:1, command: 'cache:flush'}
    - typo3-console: {copyEntryPoint:1, command: 'database:updateschema "field.add,field.change,table.add,table.change"'}
  post-deploy:
